name: Deploy on push

on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: yarn install && yarn build
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server_feedget }}
          username: ${{ secrets.ftp_username_feedget }}
          password: ${{ secrets.ftp_password_feedget }}
          server-dir: /
          local-dir: dist/
