on:
  push:
    branches:
      - main
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Build
      with:
        cache: 'yarn'
        run: yarn ci && yarn install && yarn build
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_server_feedget }}
        username: ${{ secrets.ftp_username_feedget }}
        password: ${{ secrets.ftp_password_feedget }}
        server-dir: /
